# SSH into server, pull repo and run deploy.sh script
name: Main Branch

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy to Production Host
    runs-on: ubuntu-18.04

    steps:
      - name: Run deploy script via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sh ~/config-api-gateway/api.ambalytics.cloud/deploy.sh
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          privateKey: ${{ secrets.DEPLOY_PRIVATEKEY}}
          tryKeyboard: true