---
#name: amba-analysis-stream

#networks:
#  events_kafka:
#    name: events_kafka

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "tweets:10:1,links:3:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"

  connector_twitter:
    image: twitter-connector
    container_name: connect-twitter
    depends_on:
      - kafka

  worker_twitter:
    image: twitter-worker
    container_name: worker-twitter
    depends_on:
      - connector_twitter

# https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
# for better waiting

# topicname:partition:replica