---
#name: amba-analysis-stream

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - backend


  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    hostname: kafka
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "events_unlinked:1:1,events_unlinked-discusses:3:1,events_unlinked-crossref:3:1,events_linked:1:1,events_linked-discusses:3:1,events_unknown:3:1,events_processed:1:1,events_processed-discusses:3:1,events_aggregated:3:1"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    networks:
      - backend


  mongo_db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: events
    networks:
      - backend

#    volumes:
#        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
# create this file temporary during github workflow

  connector_twitter:
    image: twitter-connector
    container_name: twitter-connector
    depends_on:
      - kafka
    networks:
      - backend

  perculator:
    image: twitter-perculator
    container_name: twitter-perculator
    cpus: 0.5
    mem_limit: 1g
    depends_on:
      - connector_twitter
    networks:
      - backend

  worker_twitter:
    image: twitter-worker
    container_name: twitter-worker
    cpus: 0.5
    depends_on:
      - connector_twitter
    networks:
      - backend

  connector_mongodb:
    image: mongodb-connector
    container_name: mongodb-connector
    depends_on:
      - mongo_db
    networks:
      - backend

  worker_pubfinder: # --build for restart
    image: pubfinder-worker # -t for building
    container_name: pubfinder-worker
    mem_limit: 1g
    depends_on:
      - kafka
    networks:
      - backend

  aggregator:
    image: aggregator
    container_name: aggregator
    depends_on:
      - kafka
    networks:
      - backend

  api:
    image: api
    container_name: api
    ports:
      - "8080:80"
    depends_on:
      - kafka
    networks:
      - backend

networks:
  backend:
    driver: bridge


# https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
# for better waiting
# processed <-> aggregated need same amount of partitions for faust to work
#
# topicname:partition:replica
# "events_unlinked:1:1, events_unlinked-discussed:3:1, events_unlinked-crossref:3:1, events_linked:1:1, events_linked-discussed:3:1, events_unknown:3:1, events_processed:1:1, events_processed-discussed:3:1, events_aggregated:1:1"