topics:

  unlinked:
    p: 1
    r: 1
    discusses:
      p: 1
      r: 1
    crossref:
      p: 1
      r: 1

  linked:
    p: 1
    r: 1
    discusses:
      p: 1
      r: 1

  unknown:
    p: 1
    r: 1

  processed:
    p: 1
    r: 1
    discusses:
      p: 1
      r: 1

  aggregated:
    p: 1
    r: 1


network:

  kafka:
    port:
      9092
    network:
      backend

  zookeeper:
    port:
      2181
    network:
      backend

  mongo_db:
    port:
      27017
    network:
      backend

mongo_db:
  mongo_db_connector:
    # todo root, run script on startup to create if not not exist
    # client.testdb.add_user('newTestUser', 'Test123', roles=[{'role':'readWrite','db':'testdb'}])
    username: mongo_db_connector
    MONGO_INITDB_ROOT_PASSWORD: example
    MONGO_INITDB_DATABASE: events